# Generated by Django 3.0.8 on 2020-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.TimeField(),
        ),
    ]
