# Generated by Django 3.0.8 on 2020-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200711_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.ImageField(upload_to=''),
        ),
    ]
