# Generated by Django 3.0.8 on 2020-07-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200711_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='link',
            new_name='photo',
        ),
    ]
