# Generated by Django 3.0.8 on 2020-07-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.CharField(default='', max_length=64),
        ),
    ]
